add create instance tests
webstudio-is/webstudio-designer pull request #13
Opened 2022-03-27 12:18 UTC by piyusharorawork

Just added few tests for create instance to be consistent with other tests . 

@kof  Let me know if there are any issues with pr

2022-03-27 13:12 UTC, kof commented on app/shared/tree-utils/create-instance.test.ts
> +      id: undefined,
can just omit the id

2022-03-27 13:13 UTC, kof commented on app/shared/tree-utils/create-instance.test.ts
> +      style: {},
can omit style and children

2022-03-27 13:13 UTC, kof commented on app/shared/tree-utils/create-instance.test.ts
> +    expect(createdInstance.id).toBeDefined();
to be a string

2022-03-27 13:15 UTC, kof commented on app/shared/tree-utils/create-instance.test.ts
> +    expect(createdInstance.children.length).toBe(1);
would want to check if the exact same child was preserved for e.g.

2022-03-27 13:17 UTC, kof commented on app/shared/tree-utils/create-instance.test.ts
> +      style: {},
would add a test in the same style that checks style is an object after creation without passing a style

2022-03-27 13:17 UTC, kof requested changes
looking good, left a few comments

2022-04-06 13:02 UTC, merged

2022-04-06 13:02 UTC, kof commented
merged, thank you!

2022-04-06 17:41 UTC, piyusharorawork commented
> merged, thank you!

@kof  I wanted to contribute more to this project , please let me know if you want me to work on any specific issue which you   are not already working on .

2022-04-06 19:28 UTC, kof commented
@piyusharorawork do you have some particular topic or area of interest? Let's chat on discord, I need to find for you something that fits your interest, experience and time!