Hide outline when preview styles
webstudio-is/webstudio-designer pull request #663
Opened 2022-12-20 09:45 UTC by TrySound

Ref https://github.com/webstudio-is/webstudio-designer/issues/625

Frequently changed style values with for example scrub makes outline look laggy because of latency between iframe and designer (where outline is rendered).

Here I subscribed to previewStyle and send undefined to hide rect. We do the same when scroll canvas and cannot update outline fast.

## Description

1. What is this PR about (link the issue and add a short description)

## Steps for reproduction

1. select instance
2. use scrub to change for example top

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [x] made a self-review
- [x] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `designer/env-check.js` if mandatory

2022-12-20 11:14 UTC, kof commented
I see a flickr https://share.descript.com/view/taP1qzTW54z

2022-12-20 11:14 UTC, kof requested changes
seems like timing is not optimal, because I see flicker with outline showing up while scrubbing

https://share.descript.com/view/taP1qzTW54z

2022-12-21 11:24 UTC, TrySound commented
Right, it's resize observer. So we may not need it at all since we won't show outline for preview style annymore.

2022-12-21 11:48 UTC, kof commented
I think resize-observer could be useful additionally in case component changes it's size in response to some property change later on

2022-12-23 07:39 UTC, TrySound commented
Changed atom type. Now resize observer passively updates rect without controlling visibility state.

2022-12-23 09:41 UTC, kof approved these changes
Tested, looking good 👍

2022-12-23 10:49 UTC, merged